######################################################################
# Automatically generated by qmake (3.0) Sat Feb 11 23:00:40 2017
######################################################################
QT       += core gui
QT += widgets

TEMPLATE = app
TARGET = WindSpeedIndicator
INCLUDEPATH += .
INCLUDEPATH += ../qwt-6.1.3/src

LIBS += -L../qwt-6.1.3/lib -lqwt

# Input
HEADERS += Compass.h
SOURCES += Compass.cpp main.cpp
